FROM rcarmo/azure-toolbox:java
MAINTAINER rcarmo
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
 && apt-get install -y openmpi-bin \
 && rm -rf /var/lib/apt/lists/*

# Anaconda 4.2.0 (Python 3.5)
USER user
RUN wget -q https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh -O /tmp/anaconda.sh \
 && sudo -u user /bin/bash /tmp/anaconda.sh -b \
 && rm /tmp/anaconda.sh

# Enable it
ENV PATH /home/user/anaconda3/bin:$PATH
RUN pip install --no-cache-dir --ignore-installed --upgrade \
      pip \
      https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp35-cp35m-linux_x86_64.whl \
      https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp35-cp35m-linux_x86_64.whl \
 && echo 'export PATH="/home/user/anaconda3/bin:$PATH"' >> /home/user/.bashrc \
 && conda install -y -c conda-forge jupyter_contrib_nbextensions 

# Restore UID so that quickstart.sh works properly
USER root

# Labels
ARG VCS_REF
ARG BUILD_DATE
LABEL org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/rcarmo/azure-toolbox"
