name: ml-py36
channels: !!python/tuple
- defaults
dependencies:
- h5py=2.6.0=np111py36_2
- jupyter=1.0.0=py36_3
- matplotlib=2.0.0=np111py36_0
- pandas=0.19.2=np111py36_0
- pandas-datareader=0.2.1=py36_0
- pillow=4.0.0=py36_0
- python=3.6.1=0
- pyyaml=3.12=py36_0
- scipy=0.19.0=np111py36_0
- seaborn=0.7.1=py36_0
- six=1.10.0=py36_0
- wheel=0.29.0=py36_0
- pip:
  - numpy>=1.10
  - pytest>=3.0.7
  - sphinx>=1.4.8
  - sphinx-rtd-theme>=0.1.9
  - twine>=1.8.1
  - gym>=0.5.2
  - pydot-ng>=1.0.0
